# Generated by Django 4.0.3 on 2022-04-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Имя участника', max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия участника', max_length=32, verbose_name='Фамилия')),
                ('img', models.ImageField(blank=True, default='contact/default.jpg', help_text='Фото участника', upload_to='contact/', verbose_name='Фото')),
                ('role', models.TextField(blank=True, help_text='Роль участника в проекте', max_length=4096, verbose_name='Роль')),
                ('description', models.CharField(blank=True, help_text='Описание участника', max_length=256, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Участника',
                'verbose_name_plural': 'Команда',
            },
        ),
    ]
