# Generated by Django 4.0.3 on 2022-04-01 13:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Описание участника', max_length=256, verbose_name='Описание'),
        ),
    ]
