# Generated by Django 4.0.3 on 2022-04-01 13:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contact_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название шаблона для поиска нужного шаблона в общем списке для данной страницы', max_length=32, verbose_name='Наимнование шаблона')),
                ('status', models.BooleanField(help_text='Статус указывет на шаблон который будет отображено на странице', verbose_name='Статус')),
                ('html', ckeditor.fields.RichTextField(verbose_name='Содержание страницы')),
            ],
            options={
                'verbose_name': 'О проекте',
                'verbose_name_plural': "описания 'О проекте'",
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, help_text='Описание участника', max_length=256, verbose_name='Описание'),
        ),
    ]
