# Generated by Django 4.0.3 on 2022-04-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_region_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Короткое описание проделанной работы', max_length=512, verbose_name='Заголовок обновления')),
                ('description', models.TextField(blank=True, help_text='Подробное описание обновления', max_length=2048, verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True, help_text='Статус указывает на шаблон который будет отображено на странице', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(help_text='Название шаблона для поиска нужного шаблона в общем списке для данной страницы', max_length=32, verbose_name='Наименование шаблона'),
        ),
        migrations.AlterField(
            model_name='about',
            name='status',
            field=models.BooleanField(help_text='Статус указывает на шаблон который будет отображено на странице', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(help_text='Название шаблона для поиска нужного шаблона в общем списке для данной страницы', max_length=32, verbose_name='Наименование шаблона'),
        ),
        migrations.AlterField(
            model_name='region',
            name='status',
            field=models.BooleanField(help_text='Статус указывает на шаблон который будет отображено на странице', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='results',
            name='name',
            field=models.CharField(help_text='Название шаблона для поиска нужного шаблона в общем списке для данной страницы', max_length=32, verbose_name='Наименование шаблона'),
        ),
        migrations.AlterField(
            model_name='results',
            name='status',
            field=models.BooleanField(help_text='Статус указывает на шаблон который будет отображено на странице', verbose_name='Статус'),
        ),
    ]
