# Generated by Django 4.0.3 on 2022-04-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_update_delete_image_alter_about_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название шаблона для поиска нужного шаблона в общем списке для данной страницы', max_length=32, verbose_name='Наименование шаблона')),
                ('img', models.ImageField(help_text='Фото', upload_to='uploads/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['date'], 'verbose_name': 'Обновление', 'verbose_name_plural': 'Обновления'},
        ),
    ]
