# Generated by Django 4.0.3 on 2022-04-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_image_alter_update_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(help_text='Статус указывает на шаблон который будет отображено на странице', verbose_name='Дата обновления'),
        ),
    ]
