# Generated by Django 4.0.3 on 2022-04-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_update_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название мероприятия, которое будет отображаться в общем списке мероприятий', max_length=512, verbose_name='Наименование мероприятия')),
                ('preview', models.ImageField(blank=True, default='contact/default.jpg', help_text='Фото, которое будет отображаться в общем списке мероприятий', upload_to='event/', verbose_name='Превью мероприятия')),
                ('description', models.TextField(help_text='Подробное описание мероприятия', max_length=2048, verbose_name='Описание')),
                ('date', models.DateField(help_text='Дата проведения мероприятия', verbose_name='Дата проведения')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['date'],
            },
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='Team',
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(help_text='Дата, когда было сделано обновление', verbose_name='Дата обновления'),
        ),
    ]
