# Generated by Django 4.0.3 on 2022-04-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_event_description_alter_event_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='preview',
            new_name='img',
        ),
    ]
