# Generated by Django 4.0.3 on 2022-04-04 11:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_preview_event_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название шаблона для поиска нужного шаблона в общем списке для данной страницы', max_length=32, verbose_name='Наименование шаблона')),
                ('status', models.BooleanField(help_text='Статус указывает на шаблон который будет отображено на странице', verbose_name='Статус')),
                ('html', ckeditor.fields.RichTextField(blank=True, verbose_name='Содержание страницы')),
            ],
            options={
                'verbose_name': 'Архив',
                'verbose_name_plural': 'Архивы',
                'abstract': False,
            },
        ),
    ]
