# Generated by Django 4.0.3 on 2022-04-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='status',
            field=models.BooleanField(help_text='Статус указывает на шаблон который будет отображено на странице', unique=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='status',
            field=models.BooleanField(help_text='Статус указывает на шаблон который будет отображено на странице', unique=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='region',
            name='status',
            field=models.BooleanField(help_text='Статус указывает на шаблон который будет отображено на странице', unique=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='results',
            name='status',
            field=models.BooleanField(help_text='Статус указывает на шаблон который будет отображено на странице', unique=True, verbose_name='Статус'),
        ),
    ]
