# Generated by Django 4.0.3 on 2022-04-04 12:05

from django.db import migrations
import main.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_about_status_alter_archive_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='status',
            field=main.fields.UniqueBooleanField(help_text='Статус указывает на шаблон который будет отображено на странице', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='status',
            field=main.fields.UniqueBooleanField(help_text='Статус указывает на шаблон который будет отображено на странице', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='region',
            name='status',
            field=main.fields.UniqueBooleanField(help_text='Статус указывает на шаблон который будет отображено на странице', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='results',
            name='status',
            field=main.fields.UniqueBooleanField(help_text='Статус указывает на шаблон который будет отображено на странице', verbose_name='Статус'),
        ),
    ]
