# Generated by Django 4.0.3 on 2022-04-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-id'], 'verbose_name': 'Участника', 'verbose_name_plural': 'Команда проекта'},
        ),
    ]
