# Generated by Django 4.0.3 on 2022-04-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_team_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, help_text='Фото, которое будет отображаться в общем списке мероприятий', upload_to='event/', verbose_name='Превью мероприятия'),
        ),
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, default='contact/default.png', help_text='Фото участника', upload_to='contact/', verbose_name='Фото'),
        ),
    ]
