# Generated by Django 4.0.3 on 2022-04-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_event_img_alter_team_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='img',
        ),
    ]
