# Generated by Django 4.0.3 on 2022-04-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_team_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, default='contact/default.png', help_text='Фото участника', upload_to='contact/', verbose_name='Фото'),
        ),
    ]
